### ISSUE TITLE
App is not running

### ISSUE THREAD

**Issue by bit0x43** [prestondunton/marvel-dialogue-nlp#4]
hI, the app is not running

**Comment by prestondunton** [comment]
Thanks for letting me know!

**Comment by prestondunton** [comment]
I'm trying to restart on Streamlit rn.  I'll update this if it gets back up.

**Comment by prestondunton** [comment]
It looks like the Streamlit team has solved the issue, although, I don't know what the problem was.  It looks like several apps on Streamlit sharing were getting stuck "In the Oven" for some reason.  Link should be working now.  

Here's the Streamlit forum:

https://discuss.streamlit.io/t/app-stuck-in-the-oven/10783

**Comment by prestondunton** [comment]
It looks like the Streamlit team has solved the issue, although, I don't know what the problem was.  It looks like several apps on Streamlit sharing were getting stuck "In the Oven" for some reason.  Link should be working now.  

Here's the Streamlit forum:

https://discuss.streamlit.io/t/app-stuck-in-the-oven/10783
